envFrom:
  - secretRef:
      name: ovh-credentials

certificatesResolvers:
  ovhresolver:  # <-- TLS resolver name
    acme:
      email: "admin@your-domain.com"
      storage: "/data/acme.json"
      dnsChallenge:
        provider: "ovh"
        propagation:
          delayBeforeChecks: 30

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ports:
  web:
    port: 8000
  websecure:
    port: 8443

service:
  type: LoadBalancer
  ports:
    web:
      port: 80 # Listen behind a loadbalancer on port 80
      targetPort: 8000
    websecure:
      port: 443 # Listen behind a loadbalancer on port 80
      targetPort: 8443

deployment:
  strategy:
    type: Recreate
